### ISSUE TITLE
[MAKENSIS] !define: "PROJECT_BASEDIR" already defined!

### ISSUE THREAD

**Issue by ostropik** [DigitalMediaServer/nsis-maven-plugin#11]
In my maven POM project i faced follow issue
<details><summary>Details</summary>
<p>

[MAKENSIS] !define: "PROJECT_BASEDIR" already defined!
[MAKENSIS] !include: error in script: "..\target\project.nsh" on line 4

</p>
</details> 

https://github.com/DigitalMediaServer/nsis-maven-plugin/blob/34cd5087e57e9b712b80f96e92e469b5e4a821dd/src/main/java/org/digitalmediaserver/nsis/GenerateHeaderfileMojo.java#L48

```java
            <plugin>
            <groupId>org.digitalmediaserver</groupId>
            <artifactId>nsis-maven-plugin</artifactId>
                <version>1.0.5</version>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>generate-headerfile</goal>
                            <goal>make</goal>
                        </goals>
                        <configuration>
                            <makensisBin>makensisw.exe</makensisBin>
                            <scriptFile>/assembly/install.nsi</scriptFile>
                            <outputFile>${project.build.finalName}-${BUILD_NUMBER}.exe</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by Nadahar** [comment]
Hi @ostropik.

It seems to me like you're using the configuration for an "old" version of the plugin. This will only work with versions before `1.0`. Some things have changed names slightly, and the logic is slightly different. 

I suspect that your particular error has to do with `injectHeaderFile` which is `true` by default. It will automatically `!include` the headerfile, which means that if you also do it in the NSIS script, it will be imported twice and everything in it will "already be defined". The README file explains all the configuration options: https://github.com/DigitalMediaServer/nsis-maven-plugin#13-skeleton-project-configuration

By the way, it seems like "Kyiv" is miss-spelled in your GitHub profile 😉 

Slava Ukraini 🇺🇦

**Comment by ostropik** [comment]
Thank you very much! Also fixed my profile data )

**Comment by Nadahar** [comment]
@ostropik Does it mean that this solved your problem? Because I'm wondering a bit how it can work. `makensisBin` is no longer a valid configuration parameter - it has been renamed to `makensisExecutable`. Also, setting it to `makensisw.exe` seems a bit strange to me, since that's the "GUI version" of `makensis` and it can't be used by this plugin (as it requires user input). Also, the default value for `makensisExecutable` is `makensis` (`.exe` is appended automatically), so there's no need to set it to that.

The idea behind the parameter is that you point it to the (relative) location where you have `makensis.exe` in your project, if you do. That way, people don't need to install NSIS to make the build, and there's no need to have `makensis.exe` on the OS path. Alternatively, just use the default and make sure that whoever builds has NSIS installed and added to the OS path.

If/when your problems have been resolved, this issue can be closed.

**Comment by ostropik** [comment]
i decided back to your advice later. was surprized by receiving fast answer)
Tomorrow i will try advice and will report you results.
Today i quiqly found workarounds and move forward with my urgent task. Have nice ...!

**Comment by ostropik** [comment]
install.nsi
```
!include MUI2.nsh
 
RequestExecutionLevel Admin

!define home ".."
!define resources "${home}\src\main\resources"
!define target "${home}\target"

!include "${target}\project.nsh"

Name "MY:COMPANY"
```
Can't understand properly. Does your advice is deletion this line [ !include "${target}\project.nsh" ] from the NSI script?

**Comment by Nadahar** [comment]
Yes, ```!include "${target}\project.nsh"``` must be removed or `injectHeaderFile` must be set to `false`. When `injectHeaderFile` is `true`, the plugin will automatically include the header file (`project.nsh`) "before the start of the script", so that it ends up being included twice - which gives the error.

The benefit of using `injectHeaderFile` is that the path to the header file will always be correct, since the plugin makes the header file, it knows exactly where it is. So, it could avoid some potential problems in that sense, but otherwise the two solutions are "equal" and it doesn't matter which one you choose. You must just make sure to use one of them, not both.

**Comment by ostropik** [comment]
Does not help(
```
           <plugin>
            <groupId>org.digitalmediaserver</groupId>
            <artifactId>nsis-maven-plugin</artifactId>
                <version>1.0.5</version>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>generate-headerfile</goal>
                            <goal>make</goal>
                        </goals>
                        <configuration>
                            <makensisBin>makensis.exe</makensisBin>
                            <scriptFile>/assembly/install.nsi</scriptFile>
                            <outputFile>${project.build.finalName}-${BUILD_NUMBER}.exe</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

```
!include MUI2.nsh
 
RequestExecutionLevel Admin

!define home ".."
!define resources "${home}\src\main\resources"
!define target "${home}\target"

Name "MY:COMPANY"

InstallDir "c:\Program Files\COMPANY\COMPANY"

Page directory
Page instfiles
```


```
--- nsis-maven-plugin:1.0.5:make (default) @ my_comp-packer ---
Executing: makensis /X!include D:\Projects\JavaProjects\MyCompany\target\project.nsh /XOutFile D:\Projects\JavaProjects\MyCompany\target\mySoft1.13.0-5-${BUILD_NUMBER}.exe /V2 D:\assembly\install.nsi
[MAKENSIS] !define: "PROJECT_BASEDIR" already defined!
[MAKENSIS] !include: error in script: "..\target\project.nsh" on line 4
[MAKENSIS] Error in script "D:\assembly\install.nsi" on line 9 -- aborting creation process
```

**Comment by Nadahar** [comment]
That's very strange. It's hard to know without seeing all the files, but I would do a search of all the relevant files for `!define PROJECT_BASEDIR` and see where it's found. It should only be found in one file, `project.nsh`, and it should only be listed there once.

The error is simply that this command (`!define PROJECT_BASEDIR\`) is attempted to be run twice.

Alternatively, turn off `injectHeaderFile` by adding 
```xml
<injectHeaderFile>false</injectHeaderFile>
```
to the `<configuration>` section in POM.xml.

**Comment by ostropik** [comment]
This was help    
```
       <plugin>
            <groupId>org.digitalmediaserver</groupId>
            <artifactId>nsis-maven-plugin</artifactId>
                <version>1.0.5</version>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>generate-headerfile</goal>
                            <goal>make</goal>
                        </goals>
                        <configuration>
                            <makensisBin>makensis.exe</makensisBin>
                            <scriptFile>${project.basedir}/assembly/install.nsi</scriptFile>
                            <outputFile>${project.build.finalName}-${BUILD_NUMBER}.exe</outputFile>
                            <injectHeaderFile>false</injectHeaderFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by Nadahar** [comment]
That's good, but I see that you still have the invalid configuration parameter `<makensisBin>` defined. The correct parameter is `<makensisExecutable>`.

**Comment by ostropik** [comment]
`<makensisExecutable>makensis.exe</makensisExecutable>`
 also works!

**Comment by ostropik** [comment]
To finalize our discussion, I can propose one improvement,

```
; Header file with project details for wl-tms-packer
; Generated from pom.xml version 1.13.0-5 on 2024-02-29 16:36:56
```
Date objDate = new Date();
System.out.println(objDate.toString());

Thu Feb 29 16:43:08 EET 2024
2024-02-29 16:36:56

Put here a universal format of date, not depending on the target machine. I faced issues using "29 **Лют** 2024". Header was generated in Win1251, and NSIS returned to me some error about encoding. Now workaround reconfigure PC regional settings.

**Comment by ostropik** [comment]
in any case, thank for support!

**Comment by Nadahar** [comment]
Ah, that's a good point 👍 The regional settings stuff is "difficult" because people from different parts of the world expects something different, but I agree that there should probably be possible to find some "universal" date format to use. The ISO 8601 format YYYY-MM-DD is intended to be "universal" and might be a good idea.

In addition it might be a good idea to write the header file with UTF-8 BOM, since NSIS will interpret text files without BOM as a local codepage. That would make it possible for the header file to include unicode characters in general, from some of POM variables for example.

**Comment by Nadahar** [comment]
@ostropik Regarding your date problem, with `29 Лют 2024` - I don't understand. I've checked the code, and it's supposed to produce a ISO 8601 compliant date. This was implemented in version `1.0`. Which version were you using when encountering this problem?

**Comment by ostropik** [comment]
Hi, sorry it could be my mistake. I have changed a lot of plugins, a lot of workarounds to solve this.
Let's close this issue)
Maybe it was in
```
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>nsis-maven-plugin</artifactId>
                <version>1.0-alpha-1</version>
```
At the start of accepting this source(not my and from the region where on PC eng-en). To solve this I performed a hundred actions. I switched between nsis versions, between plugins...
So let's close it if you check that on your solution this is ok)

**Comment by Nadahar** [comment]
@ostropik That's fine - I just wanted to fix the issue and was a bit confused when I looked at the code. I will release a new version where the header file has a UTF-8 BOM. The header file is already written as UTF-8, but NSIS interprets all files without a BOM as ANSI. So, adding the BOM should make sure that it will build even if the header file contains Unicode characters.

**Comment by Nadahar** [comment]
I just released version `1.0.6` with the UTF-8 BOM "fix": https://github.com/DigitalMediaServer/nsis-maven-plugin/releases/tag/v1.0.6

It has been released to Maven Central as well, but it's not reflected there yet. I usually takes a few hours for Maven Central to update itself and show changes.

**Comment by ostropik** [comment]
To be sure, I can only propose to prepare the environment(Win with OS specific OS lang and regional settings) with any not English language and check/exclude appearing some like this "29 Лют 2024". For this enough any Java "Hello world" app. But be afraid: once I changed OS lang to Arabic and spent one day until a colleague helped me restore all back)
But only if you have time, and don't sure about your code. Cause it can be simply my experiment's mistake.

**Comment by Nadahar** [comment]
I already tried to set my locale to Ukrainian (I already had it set to Norwegian - which isn't English - but which uses the Latin alphabet), and I couldn't reproduce it. That's when I figured out that this was already done in 3d88ed3f2f4a4022200066e2da8e111dad2a4225 which was part of version `1.0.0`:
```java
writer.writeln("; Generated from pom.xml version %1$s on %2$tF %2$tT", project.getVersion(), Calendar.getInstance());
```
It you read the documentation for `Formatter`, you will see that `%tF` is supposed to produce ISO 8601 dates, which is why I was a bit confused of how you managed to get `29 Лют 2024` from the plugin.

So, I think I've already done the testing I can, and I'm pretty sure it must have been an earlier version or a different plugin.
